CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    is_active  BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS training_type
(
    id                 BIGINT PRIMARY KEY,
    training_type_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS trainee
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth DATE,
    address       VARCHAR(255),
    user_id       BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS trainer
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialization_id BIGINT NOT NULL REFERENCES training_type (id),
    user_id           BIGINT NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS trainee_trainer
(
    trainee_id BIGINT NOT NULL REFERENCES trainee (id) ON DELETE CASCADE,
    trainer_id BIGINT NOT NULL REFERENCES trainer (id) ON DELETE CASCADE,
    PRIMARY KEY (trainee_id, trainer_id)
);

CREATE TABLE IF NOT EXISTS training
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id        BIGINT       NOT NULL REFERENCES trainee (id) ON DELETE CASCADE,
    trainer_id        BIGINT       NOT NULL REFERENCES trainer (id) ON DELETE CASCADE,
    training_name     VARCHAR(255) NOT NULL,
    training_type_id  BIGINT       NOT NULL REFERENCES training_type (id),
    training_date     DATE         NOT NULL,
    training_duration INTEGER      NOT NULL CHECK (training_duration > 0)
);
