db.url=jdbc:postgresql://localhost:5432/gymcrm
db.username=${DB_USERNAME:gymcrm}
db.password=${DB_PASSWORD:gymcrm}
db.pool-size=10

hibernate.hbm2ddl.auto=validate
hibernate.show_sql=false
hibernate.format_sql=true
