[versions]
junit-bom = "6.0.0"
spring-context = "7.1.0-M1"
lombok = "1.18.46"
jackson = "2.22.2"
logback = "1.5.18"

[libraries]
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-bom" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
spring-context = { group = "org.springframework", name = "spring-context", version.ref = "spring-context" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-datatype = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }